services:
  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432" # Expone el puerto 5432 del contenedor al host

  bot:
    build: .
    # Establece las variables de entorno directamente para asegurar su precedencia
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
      # ***** ¡LÍNEA AÑADIDA/MODIFICADA PARA FORZAR DATABASE_URL! *****
      DATABASE_URL: postgresql+asyncpg://productivity_habits_bot_user:pr0duct1v1b1tsgh25@db:5432/productivity_habits_bot_db
      # *************************************************************
    depends_on:
      - db
    # Añade un reinicio si el bot falla (opcional, pero útil para desarrollo)
    restart: on-failure
    # Mapea el directorio actual al /app dentro del contenedor para que los cambios de código sean instantáneos
    volumes:
      - .:/app:z

# Define los volúmenes a nivel global
volumes:
  db_data:
